### ISSUE TITLE
Failed to render array if it has more than one child

### ISSUE THREAD

**Issue by besthyman** [ulion/jsonform#11]
I download branch "bootstrap3" and use the following codes to show a form:

var jsonfrom = $('#jsonForm').jsonForm({
    schema: {"items": {"items": {"properties": {"bearer": {"required": true, "title": "Bearer", "type": "string"}, "slug": {"required": true, "title": "Slug", "type": "string"}}, "title": "Item", "type": "object"}, "type": "array"}}
    ,
    form: [{"items": {"items": ["items[].slug", "items[].bearer"], "type": "section"}, "title": "Bearer tokens", "type": "array"}, {"title": "Save", "type": "submit"}],
    value: {"items": [{"bearer": "b1", "slug": "s1"}, {"bearer": "b2", "slug": "s2"}]},
    onSubmit: function (errors, values) {
        alert(values);
    }
}); 

There are two children in my value, {"bearer": "b1", "slug": "s1"} and {"bearer": "b2", "slug": "s2"}. Only the first one is rendered.

**Comment by ulion** [comment]
a simple test indicate change the form element to add "key" value to
"items" for the array seems resolved the problem:

```
{
schema: {"items": {"items": {"properties": {"bearer": {"required": true,
"title": "Bearer", "type": "string"}, "slug": {"required": true, "title":
"Slug", "type": "string"}}, "title": "Item", "type": "object"}, "type":
"array"}}
,
form: [{"items": {"items": ["items[].slug", "items[].bearer"], "type":
"section"}, "title": "Bearer tokens", "type": "array", "key": "items"},
{"title": "Save", "type": "submit"}],
value: {"items": [{"bearer": "b1",  "slug": "s1"}, {"bearer": "b2", "slug":
"s2"}]},
onSubmit: function (errors, values) {
alert(values);
}
}
```

2015-05-08 10:28 GMT+08:00 besthyman notifications@github.com:

> I download branch "bootstrap3" and use the following codes to show a form:
> 
> var jsonfrom = $('#jsonForm').jsonForm({
> schema: {"items": {"items": {"properties": {"bearer": {"required": true,
> "title": "Bearer", "type": "string"}, "slug": {"required": true, "title":
> "Slug", "type": "string"}}, "title": "Item", "type": "object"}, "type":
> "array"}}
> ,
> form: [{"items": {"items": ["items[].slug", "items[].bearer"], "type":
> "section"}, "title": "Bearer tokens", "type": "array"}, {"title": "Save",
> "type": "submit"}],
> value: {"items": [{"bearer": "b1", "slug": "s1"}, {"bearer": "b2", "slug":
> "s2"}]},
> onSubmit: function (errors, values) {
> alert(values);
> }
> });
> 
> There are two children in my value, {"bearer": "b1", "slug": "s1"} and
> {"bearer": "b2", "slug": "s2"}. Only the first one is rendered.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ulion/jsonform/issues/11.

## 

Ulion
