### ISSUE TITLE
Color validation failing

### ISSUE THREAD

**Issue by mushishi78** [ulion/jsonform#14]
If you use a color picker, it fails validation with:

```
Validation errors Array[1]
  code: "UNKNOWN_FORMAT"
  message: "There is no validation function for format 'color'"
  path: "#/properties/maincolor"
```

You can see it in the console when you click the update button in the [playground example](http://ulion.github.io/jsonform/playground/?example=fields-color)

**Comment by ulion** [comment]
json schema does not support "color" format, so the example is using it in
improper way.

but you can always setup "type" to "color" in the form definition rather in
the schema for that field.

2015-06-29 17:16 GMT+08:00 Max White notifications@github.com:

> If you use a color picker, it fails validation with:
> 
> Validation errors Array[1]
>   code: "UNKNOWN_FORMAT"
>   message: "There is no validation function for format 'color'"
>   path: "#/properties/maincolor"
> 
> You can see it in the console when you click the update button in the playground
> example http://ulion.github.io/jsonform/playground/?example=fields-color
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ulion/jsonform/issues/14.

## 

Ulion

**Comment by mushishi78** [comment]
Thanks! It'd be cool if you could update the example then.

**Comment by ulion** [comment]
Updated. thx.

2015-06-29 22:00 GMT+08:00 Max White notifications@github.com:

> Thanks! It'd be cool if you could update the example then.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ulion/jsonform/issues/14#issuecomment-116674010.

## 

Ulion
