### ISSUE TITLE
Tab Arrays don't load multiple tabs with a value that has multiple members

### ISSUE THREAD

**Issue by mushishi78** [ulion/jsonform#15]
To replicate, go to [playground with tabs](http://ulion.github.io/jsonform/playground/?example=fields-tabarray) and add value:

``` json
  ,"value": {
    "friends": [
      { "nick": "Jim" },
      { "nick": "John" }
    ]
  }
```

It works for the normal array view and on the master fork.

**Comment by ulion** [comment]
Add "key": "friends" to the form definition of the tabarray, seems can fix
the problem. Without the "key", jsonform can not guess that friends array
value is just for that tabarray in the form definition.

2015-06-29 23:21 GMT+08:00 Max White notifications@github.com:

> To replicate, go to playground with tabs
> http://ulion.github.io/jsonform/playground/?example=fields-tabarray and
> add value:
> 
> ,  value: {
>     friends: [
>       { nick: 'Jim' },
>       { nick: 'John' }
>     ]
>   }
> 
> It works for the normal array view and on the master fork.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ulion/jsonform/issues/15.

## 

Ulion

**Comment by mushishi78** [comment]
Great Thanks!
