### ISSUE TITLE
V4 schema not supported by JSV

### ISSUE THREAD

**Issue by epitomus** [ulion/jsonform#17]
Problem is (I think) that the schema is converted to V4 regardless of validator (convertSchemaV3ToV4), which in the case of creating an array of 'required' fields at the top level breaks the JSV V3 validation.

I'm using z-schema now anyway, which works fine, but as JSV is still bundled and nominally supported elsewhere, it should work everywhere.

**Comment by ulion** [comment]
It did, since JSV does not support V4, it looks out of maintain and no
longer updated.

2015-07-24 10:15 GMT+08:00 epitomus notifications@github.com:

> Problem is (I think) that the schema is converted to V4 regardless of
> validator (convertSchemaV3ToV4), which in the case of creating an array of
> 'required' fields at the top level breaks the JSV V3 validation.
> 
> I'm using z-schema now anyway, which works fine, but as JSV is still
> bundled and nominally supported elsewhere, it should work everywhere.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ulion/jsonform/issues/17.

## 

Ulion

**Comment by epitomus** [comment]
Yeah, I guess the best option would be to remove support for JSV / V3.

**Comment by ulion** [comment]
I just removed JSV in my fork. thx.

2015-07-24 10:35 GMT+08:00 epitomus notifications@github.com:

> Yeah, I guess the best option would be to remove support for JSV / V3.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ulion/jsonform/issues/17#issuecomment-124295639.

## 

Ulion

**Comment by epitomus** [comment]
No probs, thanks for removing it!
